# Site Settings
theme: jekyll-theme-minimal
title: Eya Cherif
email: cherif@informatik.uni-leipzig.de
description: I am PhD student at the physics and geoscience faculty at Leipzig University and in my research I am working at the interface of Deep Learning and vegetation ecology with a focus on biodiversity monitoring.
url: "https://echerif18.github.io/"
twitter_username: Eya__Cherif
github_username:  echerif18
logo: /assets/images/img.jpg

# Site Author
author:
  name             : "Eya Cherif"
  avatar           : "img.jpg"
  location         : "Leipzig, Saxony, Germany"
  googlescholar    : "https://scholar.google.com/citations?user=8PDBlOoAAAAJ&hl=en"
  email            : "cherif[at]informatik.uni-leipzig.de"
  researchgate     : 
  github           : "echerif18"
  linkedin         :
  twitter          : "Eya__Cherif"

# Build Settings
sass:
  sass_dir: _sass
include: 
  - _pages

# Collections
# collections:
#   teaching:
#     output: true
#     permalink: /:collection/:path/
#   publications:
#     output: true
#     permalink: /:collection/:path/
#   codeanddata:
#     output: true
#     permalink: /:collection/:path/
#   portfolio:
#     output: true
#     permalink: /:collection/:path/
#   talks:
#     output: true
#     permalink: /:collection/:path/

# Build settings
markdown: kramdown
# plugins:
  # - jekyll-feed
  # - jekyll-sitemap
  # - jekyll-seo-tag
  # - jekyll-redirect-from
