# Site Settings
title: Eya Cherif
email: cherif@informatik.uni-leipzig.de
description: I am PhD student at the physics and geoscience faculty at Leipzig University and in my research I am working at the interface of Deep Learning and vegetation ecology with a focus on biodiversity monitoring.
url: "https://echerif18.github.io/"
twitter_username: Eya__Cherif
github_username:  echerif18
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM